// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaperBellStore.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace PaperBellStore.Migrations.Logs
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20251107052006_AddAppLogsTable")]
    partial class AddAppLogsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaperBellStore.Data.AppLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DeduplicationWindowMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstOccurrence")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastOccurrence")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LogEvent")
                        .HasColumnType("JSONB");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("OccurrenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Properties")
                        .HasColumnType("JSONB");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Level")
                        .HasDatabaseName("IX_AppLogs_Level");

                    b.HasIndex("MessageHash")
                        .HasDatabaseName("IX_AppLogs_MessageHash");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AppLogs_Timestamp");

                    b.HasIndex("MessageHash", "LastOccurrence")
                        .HasDatabaseName("IX_AppLogs_MessageHash_LastOccurrence");

                    b.ToTable("AppLogs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
